services:

  mongodb:
    container_name: mongo
    image: mongo:latest
    networks:
      - bot_network
    volumes:
      - mongo_data:/data/db
    restart: always
    command: mongod --auth

  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:3-management
    networks:
      - bot_network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  telegram:
    container_name: telegram-listener
    image: telegram-listener:latest
    networks:
      - bot_network
    depends_on:
      - rabbitmq
    restart: always

  from-user-listener:
    container_name: from-user-listener
    image: from-user-listener:latest
    networks:
      - bot_network
    depends_on:
      - rabbitmq
    restart: always

  to-user-listener:
    container_name: to-user-listener
    image: to-user-listener:latest
    networks:
      - bot_network
    depends_on:
      - rabbitmq
    restart: always

networks:
  bot_network:
    driver: bridge

volumes:
  mongo_data:
